### ISSUE TITLE
Minimal example does not work

### ISSUE THREAD

**Issue by AxelRHD** [DeMoorJasper/parcel-plugin-svelte#155]
# 🐛 Bug Report

Trying to start dev server or bundle will run into following error:

```
‼  Parser "parcel-plugin-svelte\lib\svelte-asset.js" failed to initialize when processing asset "App.svelte". Threw the following error:
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './compiler.js' is not defined by "exports" in D:\Dokumente\Development\node-projects\parcel-svelte\node_modules\svelte\package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:290:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:513:3)
    at resolveExports (internal/modules/cjs/loader.js:432:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:472:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (D:\Dokumente\Development\node-projects\parcel-svelte\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (D:\Dokumente\Development\node-projects\parcel-svelte\node_modules\parcel-plugin-svelte\lib\svelte-asset.js:2:33)
    at Module._compile (D:\Dokumente\Development\node-projects\parcel-svelte\node_modules\v8-compile-cache\v8-compile-cache.js:192:30) falling back to RawAsset
‼  Parser "parcel-plugin-svelte\lib\svelte-asset.js" failed to initialize when processing asset "App.svelte". Threw the following error:
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './compiler.js' is not defined by "exports" in D:\Dokumente\Development\node-projects\parcel-svelte\node_modules\svelte\package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:290:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:513:3)
    at resolveExports (internal/modules/cjs/loader.js:432:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:472:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (D:\Dokumente\Development\node-projects\parcel-svelte\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (D:\Dokumente\Development\node-projects\parcel-svelte\node_modules\parcel-plugin-svelte\lib\svelte-asset.js:2:33)
    at Module._compile (D:\Dokumente\Development\node-projects\parcel-svelte\node_modules\v8-compile-cache\v8-compile-cache.js:192:30) falling back to RawAsset
```

## 🎛 Configuration (.svelterc, package.json, cli command)

package.json:
```
{
  "name": "parcel-svelte",
  "version": "1.0.0",
  "description": "",
  "main": "main.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "parcel index.html",
    "build": "parcel build index.html"
  },
  "license": "MIT",
  "devDependencies": {
    "@babel/polyfill": "^7.12.1",
    "parcel-bundler": "^1.12.4",
    "parcel-plugin-svelte": "^4.0.6",
    "svelte": "^3.30.0"
  }
}
```

## 💻 Code Sample

index.html
```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="X-UA-Compatible" content="ie=edge" />
  <title>Parcel Plugin Svelte Example</title>
</head>
<body>
<div id="demo"></div>

<!-- This script tag points to the source of the JS file we want to load and bundle -->
<script src="main.js"></script>
</body>
</html>
```

main.js
```
import '@babel/polyfill';
import App from "./App.svelte";

const app = new App({
  target: document.getElementById('demo'),
  data: {
    name: 'world'
  }
});
```

App.svelte
```
<p>Hello, {name}!</p>

<script>
  export let name = 'Anonymous';
</script>
```

## 🌍 Your Environment

Svelte version: 3.3.0
Parcel version: 1.12.4

Node version: 14.15.1
npm version: 6.14.8

**Comment by Existenziell** [comment]
I run into exactly the same issue.
I also tried with Svelte v3.31.0

This bug was fixed in Rollup, now Parcel? :)

**Comment by abau** [comment]
Using
```
"parcel-plugin-svelte": "^4.0.8",
```
fixed it for me (cf. [here](https://github.com/DeMoorJasper/parcel-plugin-svelte/issues/153#issuecomment-731625978)).
